### ISSUE TITLE
What is the actual meaning of Lidar data ? 

### ISSUE THREAD

**Issue by jediofgever** [Sjyhne/MapAI-Competition#10]
Hi, 
I am trying to train a network for Lidar. There is confusion about Lidar data and I would appreciate if you can shed some light here. 

Typically Lidar data is presented as pointclouds, with formats such as `.pcd, .ply, .xyz` etc. Sometimes it is also presented in `.bin` formats to save space. The Lidar data seems to be present in `.tif` file.

Is this file including a projection of Lidar data (e.g. Bird-Eye View) or does it include raw X,Y,Z  distance measurements? please provide minimal code on how to extract the Lidar and get the actual point cloud in case this is indeed raw pointcloud data. 

The provided function to load lidar data returns an 2d array with 1 channel

```
l = load_lidar(lidarpath=lidar_paths[2],size=(500,500))
print(l.shape)
>> torch.Size([500, 500])
```

**Comment by Sjyhne** [comment]
Hello!

The Lidar data are stored as normalized raster data. This is why they're stored in the .tif image file format, and therefore it is not possible to extract the raw point-cloud data.

**Comment by jediofgever** [comment]
I see, thanks!. 
But why ?, 
Having an actual pointcloud could be useful in order to extract more geometrical features ( e.g.,  normals,  PFH, VFH, etc.,  [see](https://pcl.readthedocs.io/projects/tutorials/en/latest/index.html#features) ) to used for network training

**Comment by Sjyhne** [comment]
The main reason is that I only have access to the LiDAR raster data for the evaluation data, hopefully, I'll be able to acquire and add the LiDAR point clouds to the final dataset version after the competition is complete.
