### ISSUE TITLE
Evaluation pipeline exit code 137 (not enough memory)

### ISSUE THREAD

**Issue by LM239** [Sjyhne/MapAI-Competition#11]
We were testing our current model with the evaluation pipeline in our private repository, and encountered an error with exit code 137, meaning we ran out of CPU memory. Do you know if this will be an issue in the competition pipeline, or does it have more memory available than the standard?

**Comment by Sjyhne** [comment]
Hello, sorry for the late response. This will not be an issue with the evaluation pipeline, as we will use our own hardware with GPU 's.

**Comment by LM239** [comment]
Do you know how much GPU memory you have?

**Comment by LM239** [comment]
Besides, is it not a requirement that the pipeline completes successfully for a pull request, @Sjyhne ?

**Comment by Sjyhne** [comment]
I have access to at least 40GB of GPU memory. 

Yes, originally, it was a requirement. However, it seems necessary to change the requirements to you being able to run certain commands in order from your working directory. I'll update the readme when I've composed the steps necessary.

**Comment by LM239** [comment]
OK, thank you! Although for what its worth, we have managed to work around the memory issue.

**Comment by Sjyhne** [comment]
That's nice to hear! All of the evaluations will be run on the GPU, as it is much faster than using a CPU :smile:

**Comment by LM239** [comment]
Turns out we may still face some issues with limited memory. Do you still intend to modify the requirements for the pipeline run?

**Comment by LM239** [comment]
@Sjyhne Can you clarify if it is a requirement that the pipeline succeeds. If it isn't can you update the README to reflect this?

**Comment by LM239** [comment]
@Sjyhne I have a suggestion for the memory issues. Can we implement an optional flag in main.py which toggles between the complete submission and a less memory demanding one.

That way we can submit a solution which will pass the github evaluation pipeline with 99% of the performance of the full system, and you can easily run the entire model with a command line flag, e.g. `--full-submission`.

The flag could be standard across all teams to limit the hassle of figuring out exactly what it is for each team. Or perhaps teams could specify in the readme exactly which arguments should be used with main.py.
