### ISSUE TITLE
Main.py task 3 bug

### ISSUE THREAD

**Issue by LM239** [Sjyhne/MapAI-Competition#12]
The default task in main.py, task 3 which runs tasks 1+ 2 deletes the task 1 predictions before continuing to task 2. See the following code which is executed both at the start of task 1 and 2 with opts["task"] = 3. 

    task_path = pathlib.Path(args.submission_path).joinpath(f"task_{opts['task']}")
    opts_file = task_path.joinpath("opts.yaml")
    predictions_path = task_path.joinpath("predictions")
    if task_path.exists():
        shutil.rmtree(task_path.absolute())

As far as I know task 3 is never used, so maybe it is not worth it to update it. Or perhaps you can wait until the competition is over?

**Comment by LM239** [comment]
And the dataloader does not work when opts["task"] = 3

**Comment by Sjyhne** [comment]
In the evaluation pipeline, we specify the task when testing, which mitigates the issue of the data loader. I can see that we do not handle the case where the task is 3, which is unfortunate. However, as you state, I also believe we can wait until the competition is over before fixing the issue.
