### ISSUE TITLE
Are the submission figures mandatory?

### ISSUE THREAD

**Issue by LM239** [Sjyhne/MapAI-Competition#13]
Just out of curiosity, are the .png figures from plt a mandatory part of the submission in the submission path?

**Comment by Sjyhne** [comment]
Hi. So the `predicted_sample_path_png` is not a mandatory part of the submission. I'm only using the `predicted_sample_path_tif` for evaluation purposes.

The `predicted_sample_path_png` is just for visualizing the predictions and comparing them to the input image and label.
