### ISSUE TITLE
The evaluation pipeline will time out after 6 hours

### ISSUE THREAD

**Issue by LM239** [Sjyhne/MapAI-Competition#16]
There is a 6 hour limit for jobs in Github Actions. Since the main step in evaluate.yml iterates through every submission it is practically guaranteed that it will time out before the majority of submissions have been tested.

**Comment by Sjyhne** [comment]
Hello!

Yes, thank you for the heads up! 

I know this is an issue, and the fix would be using a custom runner that utilizes my GPU. However, I do not have enough time to implement it for this competition (I will do it if I arrange another one). The solution is that I will have to run the code manually myself on the GPU.

With at most 31 submissions for this competition, it should be doable.
