### ISSUE TITLE
When will the test dataset be published?

### ISSUE THREAD

**Issue by LM239** [Sjyhne/MapAI-Competition#32]
Is the test data published alongside the test results or will there some delay after the 12th before it is released?

And out of curiosity, is the evaluation going according to the schedule?

**Comment by Sjyhne** [comment]
Hello!

I will create a separate huggingface dataset with the correct train, val, and test split, so there will most likely be some delay after the evaluation results are finished!

I've dedicated time tomorrow to evaluate your models, so hopefully everything will go according to plan!
