### ISSUE TITLE
BIoU is flawed on all samples

### ISSUE THREAD

**Issue by LM239** [Sjyhne/MapAI-Competition#5]
Please change

``def biou(gt, dt, dilation_ratio=0.02)``

to
``def biou(dt, gt, dilation_ratio=0.02)``

The following code does not work as intended, otherwise:

    target = class_wise(gt, c)
    if not np.any(target):
        continue

**Comment by Sjyhne** [comment]
Yeah, I noticed the different structure between the inputs for IoU and BIoU. I believe it should be fixed in the most recent commit.

Sorry for the inconvenience.
