### ISSUE TITLE
Different metrics in evaluation.py and model_task_*.py

### ISSUE THREAD

**Issue by LM239** [Sjyhne/MapAI-Competition#9]
We are in the process of verifying the evaluation pipeline, and have noticed that the pipeline produces two sets of scores. The first set of IoU and BIoU is made in the model_task_*.py files which uses resized masks, labels and lidar (their size is opts["imagesize"] * opts["imagesize"]).

The second pair of metrics is made by evaluate.py which uses the default 500 * 500 masks with the predictions found in the submissions folder (consequently, predictions must be resized in model_task_*.py if opts["imagesize"] is not 500). 

These sets of metrics are necessarily different since both the predictions and masks differ from resizing. Therefore, I want to know which is considered the "True" score in the competition.

Am I right in guessing that the metrics obtained in the model_task_*.py files are not used in the competition? If so, can we just remove the computation of the metrics from these files altogether, since they only complicate our implementation?

More generally, is there anything we can not change in model_task_*.py, as long as we store the plotted prediction, and resized prediction in the submissions folder?

**Comment by Sjyhne** [comment]
Hello!

You are correct, the evaluate.py is the one that is used for the evaluation of your submissions. The model_task_* is to give an example of how the storing and evaluation during training can be done for the participants without much experience, hopefully lowering the threshold for participating in the competition.

As you can see in the main.py, there are a couple of mandatory requirements, which will be passed to the main.py function. Your code must handle these in the correct manner (storing them in the folder specified by the submission-folder argument). So to your last question: No, as long as everything is stored and handled correctly, then you can change whatever you want in these files.

Note: Remember that the trained model weights must be downloaded during inference, e.g. as in the example file using google drive, or something similar.
